version: '3'

services:
  elasticmq:
    image: softwaremill/elasticmq
    ports:
    - "9324:9324"
    - "9325:9325"
    volumes:
    - type: bind
      source: ./custom.conf
      target: /opt/elasticmq.conf
